### PR TITLE
Fixing constructor when argument is redis uri string

### PR DESCRIPTION
**Pull request by khmm12**
1. Fix ability to use connection as uri string
2. Use 3 latest LTS nodejs versions in travis - 4, 6, 8
3. Fix shutdown mocha process after test run

### CODE REVIEW

**Comment by ratson** [comment]
@cayasso Any reason this is not merged?

**Comment by khmm12** [comment]
It looks like library is abandoned :-(

**Comment by boblauer** [comment]
I can get this merged in for you.  Would you mind adding a test case for it first though?

**Comment by crccheck** [comment]
bump. This could also use a README example

**Comment by khmm12** [comment]
I wrote the test case, so let's continue 🙂

**Comment by khmm12** [comment]
Interesting, it seems needs to update travis config and drop down support old nodejs versions.

**Pull request merged**
